services:
  mysql:
    image: mysql:8.4
    environment:
      MYSQL_DATABASE: zfy_blog
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  meilisearch:
    image: getmeili/meilisearch:v1.13
    environment:
      MEILI_NO_ANALYTICS: "true"
      MEILI_MASTER_KEY: local-meili-key
    ports:
      - "7700:7700"

volumes:
  mysql-data:
