<?php

use App\Http\Controllers\Admin\AdminCommerceController;
use App\Http\Controllers\Admin\AdminContentAccessController;
use App\Http\Controllers\Admin\AdminContentController;
use App\Http\Controllers\Admin\AdminController;
use App\Http\Controllers\Admin\AdminExtensionUpdateController;
use App\Http\Controllers\Admin\AdminGalleryController;
use App\Http\Controllers\Admin\AdminLinkController;
use App\Http\Controllers\Admin\AdminMaintenanceController;
use App\Http\Controllers\Admin\AdminMediaController;
use App\Http\Controllers\Admin\AdminPluginController;
use App\Http\Controllers\Admin\AdminResourceController;
use App\Http\Controllers\Admin\AdminThemeController;
use App\Http\Controllers\InstallController;
use App\Http\Controllers\PaymentController;
use App\Http\Controllers\Web\AccountSecurityController;
use App\Http\Controllers\Web\AuthController;
use App\Http\Controllers\Web\CartController;
use App\Http\Controllers\Web\CommunityController;
use App\Http\Controllers\Web\ContentPasswordController;
use App\Http\Controllers\Web\ExtensionAssetController;
use App\Http\Controllers\Web\GalleryController;
use App\Http\Controllers\Web\MediaController;
use App\Http\Controllers\Web\PrivateMessageController;
use App\Http\Controllers\Web\ShipmentController;
use App\Http\Controllers\Web\SiteController;
use App\Http\Controllers\Web\SitemapController;
use App\Http\Middleware\EnsureBackendAccess;
use App\Http\Middleware\EnsureInstalled;
use App\Http\Middleware\UseContentPermalinks;
use Illuminate\Support\Facades\Route;

Route::get('/install', [InstallController::class, 'show'])->name('install.show');
Route::get('/install/status', [InstallController::class, 'status'])->name('install.status');
Route::post('/install', [InstallController::class, 'store'])->name('install.store');

Route::middleware([EnsureInstalled::class, UseContentPermalinks::class])->group(function (): void {
    Route::post('/content/{content:slug}/unlock', ContentPasswordController::class)->middleware('throttle:6,1');
    Route::get('/', [SiteController::class, 'home'])->name('home');
    Route::get('/extensions/assets/{type}/{slug}/{path}', [ExtensionAssetController::class, 'show'])->where('path', '.*')->name('extensions.asset');
    Route::get('/posts', [SiteController::class, 'channel'])->defaults('type', 'posts')->name('posts.index');
    Route::get('/images', [SiteController::class, 'channel'])->defaults('type', 'images')->name('images.index');
    Route::get('/files', [SiteController::class, 'channel'])->defaults('type', 'files')->name('files.index');
    Route::get('/c/{category:slug}', [SiteController::class, 'category'])->name('categories.show');
    Route::get('/tag/{tag:slug}', [SiteController::class, 'tag'])->name('tags.show');
    Route::get('/topic/{topic:slug}', [SiteController::class, 'topic'])->name('topics.show');
    Route::post('/content/{content:slug}/reaction', [CommunityController::class, 'reaction'])->middleware('auth')->name('contents.reaction');
    Route::post('/authors/{author}/follow', [CommunityController::class, 'follow'])->middleware('auth')->name('authors.follow');
    Route::post('/user/requests', [CommunityController::class, 'request'])->middleware(['auth', 'throttle:5,1'])->name('user.requests');
    Route::post('/user/notifications/{notification}/read', [CommunityController::class, 'readNotification'])->middleware('auth')->name('notifications.read');
    Route::post('/user/checkin', [CommunityController::class, 'checkin'])->middleware(['auth', 'throttle:10,1'])->name('user.checkin');
    Route::post('/user/recharge', [SiteController::class, 'recharge'])->middleware(['auth', 'throttle:5,1'])->name('user.recharge');
    Route::get('/content/{slug}', [SiteController::class, 'content'])->name('contents.legacy');
    Route::get('/gallery/{attachment}', [GalleryController::class, 'image'])->name('gallery.image');
    Route::get('/p/{slug}', [SiteController::class, 'page'])->name('pages.show');
    Route::get('/media/{path}', [MediaController::class, 'show'])->where('path', '.*')->name('media.show');
    Route::get('/storage/{path}', [MediaController::class, 'legacy'])->where('path', '.*')->name('media.legacy');
    Route::get('/search', [SiteController::class, 'generic'])->defaults('page', 'search')->name('search');
    Route::get('/sitemap.xml', SitemapController::class)->name('sitemap');
    Route::get('/cart/quote', [CartController::class, 'quote'])->middleware(['auth', 'throttle:60,1']);
    Route::get('/rank', [SiteController::class, 'generic'])->defaults('page', 'rank')->name('rank');
    Route::get('/vip', [SiteController::class, 'generic'])->defaults('page', 'vip')->name('vip');
    Route::get('/points-store', [SiteController::class, 'generic'])->defaults('page', 'points-store')->name('points.store');
    Route::get('/shop', [SiteController::class, 'generic'])->defaults('page', 'shop')->name('shop');
    Route::get('/cart', [SiteController::class, 'generic'])->defaults('page', 'cart')->middleware('auth')->name('cart');
    Route::middleware('auth')->controller(CartController::class)->group(function () {
        Route::post('/cart/products/{product}', 'add');
        Route::patch('/cart/items/{item}', 'update')->whereNumber('item');
        Route::delete('/cart/items/{item}', 'remove')->whereNumber('item');
        Route::post('/cart/checkout', 'checkout');
        Route::post('/user/addresses', 'saveAddress');
        Route::patch('/user/addresses/{address}', 'saveAddress')->whereNumber('address');
        Route::delete('/user/addresses/{address}', 'removeAddress')->whereNumber('address');
    });
    Route::post('/shop/{product}/buy', [SiteController::class, 'buyProduct'])->middleware('auth')->name('products.buy');
    Route::get('/authors', [SiteController::class, 'generic'])->defaults('page', 'authors')->name('authors.index');
    Route::post('/orders/{order:order_no}/receive', [ShipmentController::class, 'receive'])->middleware('auth')->name('orders.receive');
    Route::get('/author/{username}', [SiteController::class, 'generic'])->defaults('page', 'author-profile')->name('authors.show');
    Route::get('/links', [SiteController::class, 'generic'])->defaults('page', 'links')->name('links');
    Route::get('/go/{link}', [AdminLinkController::class, 'redirect'])->name('links.redirect');
    Route::post('/buy/{slug}', [SiteController::class, 'buy'])->middleware('auth')->name('contents.buy');
    Route::post('/content/{content:slug}/comments', [SiteController::class, 'storeComment'])->middleware(['auth', 'throttle:10,1'])->name('comments.store');
    Route::post('/vip/{level}/buy', [SiteController::class, 'buyVip'])->middleware('auth')->name('vip.buy');
    Route::post('/orders/{order:order_no}/pay', [SiteController::class, 'payOrder'])->middleware('auth')->name('orders.pay');
    Route::post('/orders/{order:order_no}/cancel', [SiteController::class, 'cancelOrder'])->middleware('auth')->name('orders.cancel');
    Route::put('/user/profile', [AdminResourceController::class, 'profile'])->middleware('auth')->name('user.profile');
    Route::post('/content/{content:slug}/download', [SiteController::class, 'download'])->middleware('auth')->name('downloads.create');
    Route::get('/downloads/{attachment}', [SiteController::class, 'downloadFile'])->middleware('auth:sanctum')->name('downloads.file');
    Route::post('/points-store/{item}/exchange', [SiteController::class, 'exchange'])->middleware('auth')->name('points.exchange');
    Route::post('/links', [SiteController::class, 'submitLink'])->middleware(['auth', 'throttle:5,1'])->name('links.submit');
    Route::post('/user/withdrawals', [SiteController::class, 'withdraw'])->middleware(['auth', 'throttle:5,1'])->name('withdrawals.store');
    Route::post('/orders/{order:order_no}/refund', [SiteController::class, 'refund'])->middleware('auth')->name('refunds.store');
    Route::post('/refunds/{refund}/return', [ShipmentController::class, 'returnShipment'])->middleware(['auth', 'throttle:10,1'])->name('refunds.return');

    Route::get('/login', [AuthController::class, 'login'])->name('login');
    Route::post('/login', [AuthController::class, 'authenticate'])->middleware('throttle:10,1')->name('login.store');
    Route::get('/register', [AuthController::class, 'register'])->name('register');
    Route::post('/register', [AuthController::class, 'store'])->middleware('throttle:5,1')->name('register.store');
    Route::get('/forgot-password', [AuthController::class, 'forgotPassword'])->middleware('guest')->name('password.request');
    Route::post('/forgot-password', [AuthController::class, 'sendResetLink'])->middleware(['guest', 'throttle:5,1'])->name('password.email');
    Route::get('/reset-password/{token}', [AuthController::class, 'resetPassword'])->middleware('guest')->name('password.reset');
    Route::post('/reset-password', [AuthController::class, 'updatePassword'])->middleware(['guest', 'throttle:10,1'])->name('password.update');
    Route::post('/logout', [AuthController::class, 'logout'])->name('logout');
    Route::middleware('auth')->controller(AccountSecurityController::class)->group(function () {
        Route::get('/email/verify', 'notice')->name('verification.notice');
        Route::get('/email/verify/{id}/{hash}', 'verify')->middleware(['signed', 'throttle:6,1'])->name('verification.verify');
        Route::post('/email/verification-notification', 'send')->middleware('throttle:3,1')->name('verification.send');
        Route::delete('/user/sessions/{session}', 'revokeSession');
    });

    Route::get('/user', [SiteController::class, 'generic'])->defaults('page', 'user-overview')->name('user.overview');
    Route::get('/user/orders', [SiteController::class, 'generic'])->defaults('page', 'user-orders')->name('user.orders');
    Route::get('/user/downloads', [SiteController::class, 'generic'])->defaults('page', 'user-downloads')->name('user.downloads');
    Route::get('/user/wallet', [SiteController::class, 'generic'])->defaults('page', 'user-wallet')->name('user.wallet');
    Route::get('/user/points', [SiteController::class, 'generic'])->defaults('page', 'user-points')->name('user.points');
    Route::get('/user/vip', [SiteController::class, 'generic'])->defaults('page', 'user-vip')->name('user.vip');
    Route::get('/user/settings', [SiteController::class, 'generic'])->defaults('page', 'user-settings')->name('user.settings');
    Route::get('/user/notifications', [SiteController::class, 'generic'])->defaults('page', 'user-notifications')->name('user.notifications');
    Route::get('/user/messages', [SiteController::class, 'generic'])->defaults('page', 'user-messages')->middleware('auth')->name('user.messages');
    Route::post('/user/messages', [PrivateMessageController::class, 'store'])->middleware(['auth', 'throttle:10,1'])->name('messages.send');
    Route::post('/user/messages/{message}/read', [PrivateMessageController::class, 'read'])->middleware('auth')->name('messages.read');
    Route::get('/user/favorites', [SiteController::class, 'generic'])->defaults('page', 'user-favorites')->name('user.favorites');
    Route::get('/user/author', [SiteController::class, 'generic'])->defaults('page', 'author-workspace')->name('user.author');
    Route::get('/user/editor', [SiteController::class, 'generic'])->defaults('page', 'user-editor')->middleware('auth')->name('user.editor');
    Route::post('/user/contents', [AdminContentController::class, 'submit'])->middleware(['auth', 'throttle:20,1'])->name('user.contents.store');
    Route::patch('/user/contents/{content}', [AdminContentController::class, 'submit'])->middleware(['auth', 'throttle:20,1'])->name('user.contents.update');

    Route::match(['get', 'post'], '/payments/{gateway}/notify', [PaymentController::class, 'notify'])->name('payments.notify');
    Route::post('/payments/{payment}/query', [PaymentController::class, 'query'])->name('payments.query');
    Route::get('/payments/{payment}/qr', [PaymentController::class, 'qr'])->middleware('auth')->name('payments.qr');
    Route::get('/orders/{order:order_no}/status', [PaymentController::class, 'status'])->name('orders.status');

    Route::prefix('admin')->name('admin.')->middleware(['auth', EnsureBackendAccess::class])->group(function () {
        Route::get('/themes/configuration', [AdminThemeController::class, 'index']);
        Route::get('/extensions/{type}/{slug}/update', [AdminExtensionUpdateController::class, 'source']);
        Route::put('/extensions/{type}/{slug}/update', [AdminExtensionUpdateController::class, 'save']);
        Route::post('/extensions/{type}/{slug}/update/check', [AdminExtensionUpdateController::class, 'check'])->middleware('throttle:10,1');
        Route::post('/extensions/{type}/{slug}/update/apply', [AdminExtensionUpdateController::class, 'apply'])->middleware('throttle:3,1');
        Route::post('/themes/install', [AdminThemeController::class, 'install']);
        Route::delete('/plugins/{plugin}', [AdminPluginController::class, 'uninstall']);
        Route::delete('/plugins/{plugin}/data', [AdminPluginController::class, 'purge']);
        Route::get('/link-tools/checks', [AdminLinkController::class, 'index']);
        Route::post('/link-tools/{link}/check', [AdminLinkController::class, 'check'])->middleware('throttle:15,1');
        Route::get('/maintenance/status', [AdminMaintenanceController::class, 'index']);
        Route::post('/maintenance/check-update', [AdminMaintenanceController::class, 'checkUpdate'])->middleware('throttle:5,1');
        Route::put('/maintenance/source', [AdminMaintenanceController::class, 'saveSource']);
        Route::post('/maintenance/offline', [AdminMaintenanceController::class, 'offline'])->middleware('throttle:2,1');
        Route::post('/maintenance/install-update', [AdminMaintenanceController::class, 'prepareUpdate'])->middleware('throttle:2,1');
        Route::post('/maintenance/backup', [AdminMaintenanceController::class, 'backup']);
        Route::post('/maintenance/rebuild', [AdminMaintenanceController::class, 'rebuild'])->middleware('throttle:2,1');
        Route::post('/maintenance/migrate', [AdminMaintenanceController::class, 'migrate']);
        Route::get('/maintenance/backups/{file}', [AdminMaintenanceController::class, 'download']);
        Route::put('/themes/{theme}/configuration', [AdminThemeController::class, 'save']);
        Route::post('/themes/{theme}/preview', [AdminThemeController::class, 'preview']);
        Route::delete('/themes/{theme}/installation', [AdminThemeController::class, 'uninstall']);
        Route::delete('/themes/{theme}/data', [AdminThemeController::class, 'purge']);
        Route::get('/resources/{resource}', [AdminResourceController::class, 'index']);
        Route::get('/commerce/{section}', [AdminCommerceController::class, 'index']);
        Route::patch('/commerce/{section}/{id}', [AdminCommerceController::class, 'action'])->whereNumber('id');
        Route::post('/resources/{resource}', [AdminResourceController::class, 'store']);
        Route::patch('/resources/{resource}/{id}', [AdminResourceController::class, 'update'])->whereNumber('id');
        Route::delete('/resources/{resource}/{id}', [AdminResourceController::class, 'destroy'])->whereNumber('id');
        Route::put('/settings/{group}', [AdminResourceController::class, 'saveSettings']);
        Route::put('/profile', [AdminResourceController::class, 'profile']);
        Route::post('/plugins/install', [AdminPluginController::class, 'install']);
        Route::get('/plugins/configuration', [AdminPluginController::class, 'settings']);
        Route::put('/plugins/{plugin}/configuration', [AdminPluginController::class, 'save']);
        Route::get('/', [AdminController::class, 'page'])->defaults('section', 'dashboard')->name('dashboard');
        Route::post('/contents', [AdminContentController::class, 'store'])->name('contents.store');
        Route::put('/contents/{content}/access', [AdminContentAccessController::class, 'update']);
        Route::get('/contents/{content}/gallery', [AdminGalleryController::class, 'index']);
        Route::post('/contents/{content}/gallery', [AdminGalleryController::class, 'upload']);
        Route::put('/contents/{content}/gallery', [AdminGalleryController::class, 'save']);
        Route::post('/contents/{content}/attachments', [AdminContentAccessController::class, 'upload']);
        Route::delete('/contents/{content}/attachments/{attachment}', [AdminContentAccessController::class, 'destroy']);
        Route::patch('/contents/{content}', [AdminContentController::class, 'update'])->name('contents.update');
        Route::patch('/contents/{content}/settings', [AdminContentController::class, 'settings'])->name('contents.settings');
        Route::patch('/contents/{content}/status', [AdminContentController::class, 'status'])->name('contents.status');
        Route::delete('/contents/{content}', [AdminContentController::class, 'destroy'])->name('contents.destroy');
        Route::post('/contents/preview', [AdminContentController::class, 'preview'])->name('contents.preview');
        Route::get('/editor/autosave', [AdminContentController::class, 'autosaveState'])->name('editor.autosave.state');
        Route::post('/editor/autosave', [AdminContentController::class, 'autosave'])->name('editor.autosave');
        Route::delete('/editor/autosave/{revision}', [AdminContentController::class, 'discardAutosave'])->name('editor.autosave.discard');
        Route::post('/editor/presentation-defaults', [AdminController::class, 'saveEditorPresentationDefaults'])->name('editor.presentation-defaults');
        Route::get('/contents/{content}/revisions', [AdminContentController::class, 'revisions'])->name('contents.revisions');
        Route::get('/contents/{content}/revisions/{revision}', [AdminContentController::class, 'revision'])->name('contents.revisions.show');
        Route::post('/contents/{content}/revisions/{revision}/restore', [AdminContentController::class, 'restoreRevision'])->name('contents.revisions.restore');
        Route::post('/contents/{content}/revisions/{revision}/reject', [AdminContentController::class, 'rejectRevision']);
        Route::get('/media/library', [AdminMediaController::class, 'index'])->name('media.library');
        Route::post('/media/upload', [AdminMediaController::class, 'store'])->name('media.upload');
        Route::delete('/media/{media}', [AdminMediaController::class, 'destroy'])->name('media.destroy');
        Route::get('/{section}', [AdminController::class, 'page'])
            ->where('section', '[A-Za-z0-9-]+')
            ->name('section');
        Route::post('/themes/activate', [AdminController::class, 'activateTheme'])->name('themes.activate');
        Route::post('/themes/{theme}/settings', [AdminController::class, 'saveThemeSetting'])->name('themes.settings');
        Route::post('/page-builder/{layout}', [AdminController::class, 'savePageLayout'])->name('page-builder.save');
        Route::post('/plugins/{plugin}/toggle', [AdminController::class, 'togglePlugin'])->name('plugins.toggle');
        Route::post('/plugins/{plugin}/settings', [AdminController::class, 'savePluginSetting'])->name('plugins.settings');
    });
    Route::get('/{contentBase}/{slug}', [SiteController::class, 'permalink'])->where('contentBase', '[a-z][a-z0-9-]{0,39}')->name('contents.show');
});
