<?php

return [
    'encoding' => 'UTF-8',
    'finalize' => true,
    'ignoreNonStrings' => false,
    'cachePath' => storage_path('app/purifier'),
    'cacheFileMode' => 0755,
    'settings' => [
        'default' => [
            'HTML.Doctype' => 'HTML 4.01 Transitional',
            'HTML.Allowed' => implode(',', [
                'h1[id|class],h2[id|class],h3[id|class],h4[id|class],h5[id|class],h6[id|class]',
                'p[class|style|align],br,hr[class]',
                'strong[class],b[class],em[class],i[class],s[class],del[class],sup[id|class]',
                'button[type|class|data-copy-text|aria-label|title]',
                'blockquote[class],pre[class|data-enlighter-language|data-enlighter-title],code[class|data-enlighter-language|data-enlighter-theme|data-enlighter-highlight|data-enlighter-linenumbers|data-enlighter-lineoffset|data-enlighter-title|data-enlighter-group]',
                'ul[class],ol[class],li[id|class]',
                'a[href|title|target|rel|class]',
                'img[src|alt|title|width|height|class]',
                'iframe[src|class|width|height]',
                'joe-mp3[name|url|cover|theme|autoplay]',
                'joe-music[id|color|autoplay]',
                'joe-mlist[id|color|autoplay]',
                'audio[src|class|controls|preload]',
                'video[src|class|controls|preload|poster]',
                'source[src|type]',
                'table[class],thead[class],tbody[class],tr[class],th[class|colspan|rowspan],td[class|colspan|rowspan]',
                'div[class|style|data-color|data-zfy-time-format|data-isclose|role]',
                'span[class|style|aria-hidden],font[color|size|face],small[class]',
            ]),
            'Attr.AllowedFrameTargets' => ['_blank'],
            'Attr.EnableID' => true,
            'AutoFormat.AutoParagraph' => false,
            'AutoFormat.RemoveEmpty' => false,
            'CSS.AllowedProperties' => ['width', 'border-color', 'background-color', 'color', 'font-size', 'text-align'],
            'HTML.SafeIframe' => true,
            'URI.SafeIframeRegexp' => '%^https://player\.bilibili\.com/%',
        ],
        'custom_definition' => [
            'id' => 'zfy-html5-media',
            'rev' => 10,
            'debug' => false,
            'elements' => [
                ['button', 'Inline', 'Inline', 'Common', [
                    'type' => 'Enum#button',
                    'data-copy-text' => 'Text',
                    'aria-label' => 'Text',
                    'title' => 'Text',
                ]],
                ['joe-music', 'Block', 'Flow', 'Common', [
                    'id' => 'Text',
                    'color' => 'Text',
                    'autoplay' => 'Text',
                ]],
                ['joe-mp3', 'Block', 'Flow', 'Common', [
                    'name' => 'Text',
                    'url' => 'URI',
                    'cover' => 'URI',
                    'theme' => 'Text',
                    'autoplay' => 'Text',
                ]],
                ['joe-mlist', 'Block', 'Flow', 'Common', [
                    'id' => 'Text',
                    'color' => 'Text',
                    'autoplay' => 'Text',
                ]],
                ['audio', 'Block', 'Optional: (source, Flow) | (Flow, source) | Flow', 'Common', [
                    'src' => 'URI',
                    'preload' => 'Enum#auto,metadata,none',
                    'controls' => 'Bool',
                ]],
                ['video', 'Block', 'Optional: (source, Flow) | (Flow, source) | Flow', 'Common', [
                    'src' => 'URI',
                    'poster' => 'URI',
                    'preload' => 'Enum#auto,metadata,none',
                    'controls' => 'Bool',
                ]],
                ['source', 'Block', 'Flow', 'Common', [
                    'src' => 'URI',
                    'type' => 'Text',
                ]],
            ],
            'attributes' => [
                ['div', 'data-color', 'Text'],
                ['div', 'data-start-color', 'Text'],
                ['div', 'data-end-color', 'Text'],
                ['div', 'data-zfy-time-format', 'Text'],
                ['div', 'data-isclose', 'Text'],
                ['div', 'role', 'Text'],
                ['span', 'aria-hidden', 'Text'],
                ['pre', 'data-enlighter-language', 'Text'],
                ['pre', 'data-enlighter-title', 'Text'],
                ['code', 'data-enlighter-language', 'Text'],
                ['code', 'data-enlighter-theme', 'Text'],
                ['code', 'data-enlighter-highlight', 'Text'],
                ['code', 'data-enlighter-linenumbers', 'Text'],
                ['code', 'data-enlighter-lineoffset', 'Text'],
                ['code', 'data-enlighter-title', 'Text'],
                ['code', 'data-enlighter-group', 'Text'],
            ],
        ],
    ],
];
