restart.include.json=/com.alibaba.fastjson2.*.jar
restart.exclude.druid=/com.alibaba.druid.*.jar
restart.exclude.datasource=/com.ruoyi.framework.datasource.*.jar
restart.exclude.config=/com.ruoyi.framework.config.*.jar
restart.exclude.properties=/com.ruoyi.framework.config.properties.*.jar