export const markdownThemeOptions = [
    ['juejin', '掘金'],
    ['github', 'GitHub'],
    ['smartblue', '智慧蓝'],
    ['cyanosis', '青黛'],
    ['channing-cyan', 'Channing 青'],
    ['fancy', 'Fancy'],
    ['hydrogen', '氢气'],
    ['condensed-night-purple', '凝夜紫'],
    ['greenwillow', '绿柳'],
    ['v-green', 'V 绿'],
    ['vue-pro', 'Vue Pro'],
    ['healer-readable', 'Healer'],
    ['mk-cute', '可爱风'],
    ['jzman', 'JZMAN'],
    ['geek-black', '极客黑'],
    ['awesome-green', '极客绿'],
    ['qklhk-chocolate', '巧克力'],
    ['orange', '橙心'],
    ['scrolls-light', '卷轴浅色'],
    ['simplicity-green', '简洁绿'],
    ['arknights', '明日方舟'],
    ['vuepress', 'VuePress'],
    ['Chinese-red', '中国红'],
    ['nico', 'Nico'],
    ['devui-blue', 'DevUI 蓝'],
    ['serene-rose', '静谧玫瑰'],
    ['z-blue', 'Z 蓝'],
    ['minimalism', '极简'],
    ['koi', '锦鲤'],
    ['yu', '雨'],
    ['lilsnake', '小蛇'],
    ['keepnice', 'Keep Nice'],
].map(([value, label]) => ({ value, label }));

export const codeThemeOptions = [
    { value: 'atom-one-dark', label: 'Atom One Dark' },
    { value: 'atom-one-light', label: 'Atom One Light' },
    { value: 'github', label: 'GitHub' },
    { value: 'github-dark', label: 'GitHub Dark' },
    { value: 'monokai', label: 'Monokai' },
    { value: 'tokyo-night-dark', label: 'Tokyo Night' },
    { value: 'stackoverflow-light', label: 'Stack Overflow' },
    { value: 'androidstudio', label: 'Android Studio' },
    { value: 'base16/tomorrow-night', label: 'Tomorrow Night' },
];
