import type { ZfyIconName } from '../icons/zfyIconSet';
import type { EditorTool } from './types';

const toolIconMap: Record<string, ZfyIconName> = {
    undo: 'undo',
    redo: 'redo',
    bold: 'bold',
    italic: 'italic',
    strike: 'strike',
    'inline-code': 'inlineCode',
    heading: 'heading',
    h1: 'heading',
    h2: 'heading',
    h3: 'heading',
    h4: 'heading',
    h5: 'heading',
    h6: 'heading',
    quote: 'quote',
    'ordered-list': 'orderedList',
    'unordered-list': 'unorderedList',
    'task-list': 'taskList',
    hr: 'divider',
    link: 'link',
    image: 'image',
    table: 'table',
    'code-block': 'codeBlock',
    html: 'html',
    time: 'time',
    indent: 'indent',
    characters: 'symbols',
    emoji: 'emoji',
    'zfy-alert': 'alert',
    'zfy-callout': 'callout',
    'zfy-quote': 'quote',
    'zfy-mtitle': 'centerTitle',
    'zfy-card-default': 'card',
    'zfy-card-list': 'cards',
    'zfy-card-describe': 'describe',
    'zfy-message': 'message',
    'zfy-progress': 'progress',
    'zfy-collapse': 'collapse',
    'zfy-tabs': 'tabs',
    'zfy-bilibili': 'video',
    'zfy-dplayer': 'play',
    'zfy-music-list': 'musicList',
    'zfy-music': 'music',
    'zfy-mp3': 'audio',
    'zfy-cloud': 'cloud',
    'zfy-button': 'button',
    'zfy-abtn': 'magicButton',
    'zfy-anote': 'noteButton',
    'zfy-dotted': 'dotted',
    'zfy-timeline': 'timeline',
    'zfy-copy': 'copy',
    'zfy-lamp': 'lamp',
    'zfy-grid': 'grid',
    'zfy-hide': 'hide',
    clean: 'clean',
    download: 'download',
    fullscreen: 'fullscreen',
    preview: 'preview',
    save: 'save',
    publish: 'publish',
};

const legacyIconMap: Record<string, ZfyIconName> = {
    Back: 'undo',
    Right: 'redo',
    EditPen: 'bold',
    Edit: 'italic',
    Minus: 'divider',
    Tickets: 'inlineCode',
    Menu: 'heading',
    ChatLineSquare: 'quote',
    Sort: 'orderedList',
    List: 'unorderedList',
    Finished: 'taskList',
    Link: 'link',
    Picture: 'image',
    Grid: 'grid',
    DocumentCopy: 'copy',
    Collection: 'html',
    Timer: 'time',
    DArrowRight: 'indent',
    Star: 'symbols',
    Sunny: 'emoji',
    Delete: 'clean',
    Download: 'download',
    FullScreen: 'fullscreen',
    View: 'preview',
};

export function iconForEditorTool(tool: EditorTool): ZfyIconName {
    return toolIconMap[tool.id] || (tool.icon ? legacyIconMap[tool.icon] : null) || 'component';
}
